name: Clair Action Test
on:
  push:
    branches:
      - 'main'

jobs:
  clair-execute:
    name: Clair Scan
    runs-on: ubuntu-latest
    steps:
      - name: Clair Scan
        uses: santander-group/clair-scan-action@main
        with:
          image: vulnerables/web-dvwa
          local: no
          report_format: json
          report_path: clair-report.json
          updater: debian